apiVersion: v1
kind: Service
metadata:
  name: docker-app
  labels:
    app: docker-app
spec:
  type: NodePort
  selector:
    app: docker-app
  ports:
    - protocol: TCP
      port: 3050
      targetPort: 3000
      nodePort: 31000